# Site settings
title: Life Operation
email: jypark@apache.org
description: > # this means to ignore newlines until "baseurl:"
    Newbie Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eminency.github.io" # the base hostname & protocol for your site
github_username:  eminency

# Build settings
markdown: kramdown
timezone: Asia/Seoul
